services:
  mongoDB:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
  rabbitMQ:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672